language: clojure

script: lein all test

before_install:
  - git submodule update --init --recursive
  - yes | sudo lein upgrade

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

sudo: required

cache:
  directories:
    - $HOME/.m2