language: clojure

script: lein test-$CLJ

before_install:
  - git submodule update --init --recursive
  - yes | sudo lein upgrade

matrix:
  include:
  - jdk: openjdk11
    env: CLJ=clj
  - jdk: openjdk11
    env: CLJ=cljs
  - jdk: oraclejdk11
    env: CLJ=clj
  - jdk: oraclejdk11
    env: CLJ=cljs

sudo: required

cache:
  directories:
    - $HOME/.m2
